name: Test

on: [push]

jobs:
  build:
    runs-on:  ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
    - uses: abatilo/actions-poetry@v2

    - name: Install dependencies
      run: |
        poetry install --all-extras

    - name: Lint
      run: poe lint

    - name: Test
      run: poe test
