name: Test

on: [push]

jobs:
  build:
    runs-on:  ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Lint
      run: uv run lint

    - name: Test
      run: uv run test
